# Generated by Django 2.1.7 on 2019-03-13 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='n_comments',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='n_pingback',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
