# Generated by Django 2.1.7 on 2019-03-14 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190313_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 14, 5, 34, 11, 860556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
