# Generated by Django 2.1.7 on 2019-03-14 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190314_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
